### ISSUE TITLE
Prepare site for after the conference

### ISSUE THREAD

**Issue by marcoow** [mainmatter/eurorust.eu#201]
Friday night when the conference ends we should change the site into one that thanks the sponsors and gives an outlook to next year.

# TODO

- [x] move the existing page as it is into /2022 so that it is accessible there in its current form
- [x] change the landing page:
  - [x] remove the "get your tickets" button
  - [x] change text at the top ("OCTOBER 13-14, 2022BERLIN & ONLINE") to "WE'LL BE BACK in 2023" (black on white), "October 12-13"
  - [x] remove headline of "The Talks" section (but leave the topics list)
  - [x] change headline of "Our Speakers" to "Past Speakers", remove the talks and links to speaker bios, just leave the Twitter and web links
  - [x] remove schedule
  - [x] remove conference venue and closing diner information
  - [x] remove the "Premier partners", "partners", etc. headings from the sponsors list and put all sponsors on the same level with the same size
  - [x] in the footer, remove sponsorships, accessibility, covid policy, add "2022" to link to the copied page for this year (see above)
